### PR TITLE
Added error handling as documented by gulp-sass

### PR DESCRIPTION
**Pull request by rburgt**
https://www.npmjs.com/package/gulp-sass#basic-usage

### CODE REVIEW

**Comment by kaspereden** [comment]
@rburgt the build fails

**Comment by rburgt** [comment]
@kaspereden this is also happening on the current released version

**Comment by kaspereden** [comment]
@rburgt  
Crap :(

**Comment by kaspereden** [comment]
I had locally the same issue, and the problem seemed to be a wrong version of yeoman. 👎

**Comment by kaspereden** [comment]
should work now

**Pull request merged**
