### PR TITLE
Feature/#29

### PR DESCRIPTION
**Pull request by PizzaPete**
Changed the Man into the Incentronaut.

More art can be added in the art.js file.

### CODE REVIEW

**Comment by PizzaPete** [comment]
@127001  does this meet your expectations?

**Comment by kaspereden** [comment]
Almost perfect

image

**Comment by kaspereden** [comment]
Changed into a smaller image

```
     3, 2, 1, Ignition!

          Lift-off!

         `.--:::--.`          
      `-/+++++++++++/:.       
    `:+++++++++++++++++/-     
   ./++++++++++++++++++++:    
  `/++//:------------:/+++:   
`:/++:`                ./++/- 
-+++/                   .++++`
-+++/                   `++++`
-+++/                  `:++++`
./++/          .:-....-//+++/`
  /++.         -::-----.:++-  
  /+++:-.````````````.-/+++-  
  /++++++++++++++++++++++++-  
`.``...-------::-------...``. 
.+++/////::::::::::::////+++/ 
.+++++++++++++++++++++++++++/ 
 `..---::::::::::::::::---..  
```

**Comment by kaspereden** [comment]
👍

**Comment by PizzaPete** [comment]
Looks good!

**Pull request merged**
